# Banner que se muestra a la hora de cargar el spring
#
spring:
  banner:
    location: classpath:banner.txt
  jpa:
    properties: # 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true # muestra el sql en pantalla cuando se realice las querys
    hibernate: # al cargar el servidor las entitys se entienden con las tablas
      #ddl-auto: create-drop 
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy # Como se realizan las consultas
  datasource: # Permite manejo con la base de datos
    url:  jdbc:mysql://localhost:3306/spring_ninja
    username: root
    password: root
 
server:
  port: 8081 # Server HTTP port.
  error:
    whitelabel:
      enabled:  true  #para mostrar o ocultar la pagina de error apachetomcat.   
