# Banner que se muestra a la hora de cargar el spring
#
spring:
  banner:
    location: classpath:banner.txt
    
server:
  port: 8081 # Server HTTP port.
  error:
    whitelabel:
      enabled:  true  #para mostrar o ocultar la pagina de error apachetomcat.   